// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package wosh_terminal_identity_store

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

//go:wasmimport wosh:terminal/identity-store [async-lower]public-key
func wasm_import_public_key(arg0 uintptr) int32

func PublicKey() witTypes.Result[[]uint8, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_public_key(returnArea)))
	var result witTypes.Result[[]uint8, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, string](value)
	case 1:
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[[]uint8, string](value0)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wosh:terminal/identity-store [async-lower]sign
func wasm_import_sign(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func Sign(data []uint8) witTypes.Result[[]uint8, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	data0 := unsafe.Pointer(unsafe.SliceData(data))
	pinner.Pin(data0)

	witAsync.SubtaskWait(uint32(wasm_import_sign(uintptr(data0), uint32(len(data)), returnArea)))
	var result witTypes.Result[[]uint8, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, string](value)
	case 1:
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[[]uint8, string](value1)
	default:
		panic("unreachable")
	}

	return result

}
