// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package wosh_terminal_identity_store

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/polymorph_webcrypto_signature"
)

type SigningKey = polymorph_webcrypto_signature.SigningKey
type VerifyingKey = polymorph_webcrypto_signature.VerifyingKey

//go:wasmimport wosh:terminal/identity-store [async-lower]identity
func wasm_import_identity(arg0 uintptr) int32

func Identity() witTypes.Result[witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey], string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_identity(returnArea)))
	var result witTypes.Result[witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey], string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey], string](witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey]{polymorph_webcrypto_signature.SigningKeyFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), polymorph_webcrypto_signature.VerifyingKeyFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 1*4))))))})
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey], string](value)
	default:
		panic("unreachable")
	}

	return result

}
