// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package polymorph_iroh_identity_generate

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/polymorph_iroh_identity"
	"wit_component/polymorph_iroh_types"
)

type Error = polymorph_iroh_types.Error
type Identity = polymorph_iroh_identity.Identity

//go:wasmimport polymorph:iroh/identity-generate@0.1.0 [async-lower]generate
func wasm_import_generate(arg0 uintptr) int32

func Generate() witTypes.Result[*polymorph_iroh_identity.Identity, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_generate(returnArea)))
	var result witTypes.Result[*polymorph_iroh_identity.Identity, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*polymorph_iroh_identity.Identity, polymorph_iroh_types.Error](polymorph_iroh_identity.IdentityFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorTimedOut(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorNotSupported(value1)

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInUse(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value3)

		case 7:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value4)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*polymorph_iroh_identity.Identity, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}
