// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package polymorph_iroh_types

import ()

// An endpoint identity: exactly 32 bytes, an Ed25519 public key.
//
// The key is the address: connections are requested by, and
// authenticated against, this value. A `list<u8>` of any other
// length is rejected with `error.invalid-argument` wherever an
// `endpoint-id` is accepted.
type EndpointId = []uint8

// An opaque address for an unrecognized transport (upstream iroh's
// `CustomAddr`).
type CustomAddr struct {
	// The transport's numeric identifier.
	Id uint64
	// Opaque address data, meaningful to that transport.
	Data []uint8
}

const (
	// A relay server the peer keeps a connection open to: an
	// `http` or `https` base URL. Use one spelling per relay —
	// implementations normalize at most minimally (equality is
	// implementation-defined beyond the exact string).
	TransportAddrRelay uint8 = 0
	// A direct socket address, `ip:port`: IPv4 dotted-quad or
	// bracketed IPv6 (`[2001:db8::1]:443`); IPv6 scope-id support
	// is implementation-defined. An entry that does not parse is
	// ignored for dialing but preserved.
	TransportAddrIp uint8 = 1
	// Reachable over a WebRTC data channel, negotiated by signaling
	// through the given relay server (a URL). Both peers must hold
	// a connection to that relay. An entry of this kind is an
	// upgrade hint, not a dial target: the connection starts on
	// the relay and moves to the channel once it opens (see
	// `endpoint.connect`). This case is this package's own; it
	// maps to a `custom` entry in upstream iroh address records
	// (the mapping is fixed when discovery lands).
	TransportAddrWebrtc uint8 = 2
	// An address for a transport this package predates.
	TransportAddrCustom uint8 = 3
)

// One way a peer may be reached, mirroring upstream iroh's
// `TransportAddr`.
//
// The `custom` case is the extension point: address kinds that do
// not exist yet travel as an opaque payload under a numeric
// transport ID, so they survive round trips through parties that
// do not understand them.
type TransportAddr struct {
	tag   uint8
	value any
}

func (self TransportAddr) Tag() uint8 {
	return self.tag
}

func (self TransportAddr) Relay() string {
	if self.tag != TransportAddrRelay {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self TransportAddr) Ip() string {
	if self.tag != TransportAddrIp {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self TransportAddr) Webrtc() string {
	if self.tag != TransportAddrWebrtc {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self TransportAddr) Custom() CustomAddr {
	if self.tag != TransportAddrCustom {
		panic("tag mismatch")
	}
	return self.value.(CustomAddr)
}

func MakeTransportAddrRelay(value string) TransportAddr {
	return TransportAddr{TransportAddrRelay, value}
}
func MakeTransportAddrIp(value string) TransportAddr {
	return TransportAddr{TransportAddrIp, value}
}
func MakeTransportAddrWebrtc(value string) TransportAddr {
	return TransportAddr{TransportAddrWebrtc, value}
}
func MakeTransportAddrCustom(value CustomAddr) TransportAddr {
	return TransportAddr{TransportAddrCustom, value}
}

// Where to find a peer.
//
// Only `endpoint-id` identifies the peer; `addrs` are hints for
// reaching it. A connection is authenticated against `endpoint-id`
// regardless of which path reached the peer.
type EndpointAddr struct {
	// The peer's identity.
	EndpointId []uint8
	// Ways the peer may be reachable, in no particular order.
	// Unrecognized `custom` entries are ignored for dialing but
	// preserved.
	Addrs []TransportAddr
}

const (
	// The handshake is in progress.
	ConnectionStateConnecting uint8 = 0
	// The connection is open: streams operate normally.
	ConnectionStateOpen uint8 = 1
	// The connection is closed. Terminal.
	ConnectionStateClosed uint8 = 2
)

// The lifecycle state of a `connection`.
type ConnectionState = uint8

// The contents of a received QUIC application close (RFC 9000
// CONNECTION_CLOSE carrying an application-supplied code and
// reason). Read it with `connection.wait-closed`.
//
// A `close-info` exists only when the peer's application close
// arrived: a connection that ends any other way — closed locally,
// idle-timed-out, or lost to a transport error — has none, and
// implementations never invent one.
type CloseInfo struct {
	// The peer's application close code. QUIC carries codes up
	// to 2^62 - 1.
	Code uint64
	// The peer's close reason. QUIC carries raw bytes; bytes that
	// are not valid UTF-8 are replaced with U+FFFD.
	Reason string
}

const (
	// Datagrams travel through a relay server.
	PathKindRelay uint8 = 0
	// Datagrams travel over a direct UDP socket.
	PathKindIp uint8 = 1
	// Datagrams travel over a WebRTC data channel.
	PathKindWebrtc uint8 = 2
)

// The wire currently carrying a `connection`'s packets. Read it
// with `connection.path`; it can change over the connection's
// life (see `connect` for the upgrade behavior).
type PathKind = uint8

const (
	// The endpoint, connection, or stream was closed before the
	// operation completed. When the peer closed the connection,
	// `connection.wait-closed` reports its application close.
	ErrorClosed uint8 = 0
	// The peer reset the stream. The payload is the application
	// reset code.
	ErrorReset uint8 = 1
	// Connection establishment failed: the relay was unreachable,
	// the handshake failed, or the peer refused the connection or
	// every offered ALPN.
	ErrorConnectFailed uint8 = 2
	// The attempt timed out: the peer, or the relay being opened,
	// did not answer within the deadline.
	ErrorTimedOut uint8 = 3
	// The deployment does not serve a capability the operation
	// needs: a transport this host does not provide.
	ErrorNotSupported uint8 = 4
	// The operation conflicts with another user of the stream
	// half: a `read` or `write` already in flight, or a
	// `read-via-stream`/`write-via-stream` claim.
	ErrorInUse uint8 = 5
	// A supplied argument is invalid: an `endpoint-id` that is not
	// 32 bytes, or a malformed relay URL. The operation had no
	// effect.
	ErrorInvalidArgument uint8 = 6
	// An implementation-specific failure.
	ErrorOther uint8 = 7
)

// Errors surfaced by the endpoint surface. The `string` payloads
// are human-readable diagnostics for logging; do not match on
// their contents.
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Reset() uint64 {
	if self.tag != ErrorReset {
		panic("tag mismatch")
	}
	return self.value.(uint64)
}
func (self Error) ConnectFailed() string {
	if self.tag != ErrorConnectFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) TimedOut() string {
	if self.tag != ErrorTimedOut {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) NotSupported() string {
	if self.tag != ErrorNotSupported {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) InUse() string {
	if self.tag != ErrorInUse {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) InvalidArgument() string {
	if self.tag != ErrorInvalidArgument {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorClosed() Error {
	return Error{ErrorClosed, nil}
}
func MakeErrorReset(value uint64) Error {
	return Error{ErrorReset, value}
}
func MakeErrorConnectFailed(value string) Error {
	return Error{ErrorConnectFailed, value}
}
func MakeErrorTimedOut(value string) Error {
	return Error{ErrorTimedOut, value}
}
func MakeErrorNotSupported(value string) Error {
	return Error{ErrorNotSupported, value}
}
func MakeErrorInUse(value string) Error {
	return Error{ErrorInUse, value}
}
func MakeErrorInvalidArgument(value string) Error {
	return Error{ErrorInvalidArgument, value}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}
