// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     irsh:ssh-engine
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_irsh_ssh_engine_ssh"
	"wit_component/irsh_ssh_engine_ssh"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (3 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport irsh:ssh-engine/ssh#[static]session.connect
func wasm_export_irsh_ssh_engine_ssh_static_session_connect(arg0 uintptr, arg1 uint32, arg2 int32, arg3 int32) int32 {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	witRuntime.Unpin()
	result := export_irsh_ssh_engine_ssh.SessionConnect(value, uint16(arg2), uint16(arg3))
	return (result).TakeHandle()

}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.authenticate
func wasm_export_irsh_ssh_engine_ssh_method_session_authenticate(arg0 uintptr, arg1 uintptr, arg2 uint32) {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg1)), arg2)
	witRuntime.Unpin()
	(export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).Authenticate(value)

}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.feed
func wasm_export_irsh_ssh_engine_ssh_method_session_feed(arg0 uintptr, arg1 uintptr, arg2 uint32) {

	value := unsafe.Slice((*uint8)(unsafe.Pointer(arg1)), arg2)
	witRuntime.Unpin()
	(export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).Feed(value)

}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.drain
func wasm_export_irsh_ssh_engine_ssh_method_session_drain(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).Drain()
	data := unsafe.Pointer(unsafe.SliceData(result))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(data)))
	return exportReturnArea

}

//go:wasmexport cabi_post_irsh:ssh-engine/ssh#[method]session.drain
func wasm_export_post_return_irsh_ssh_engine_ssh_method_session_drain(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.pump
func wasm_export_irsh_ssh_engine_ssh_method_session_pump(arg0 uintptr) {

	(export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).Pump()

}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.status
func wasm_export_irsh_ssh_engine_ssh_method_session_status(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).Status()

	switch result.Tag() {
	case irsh_ssh_engine_ssh.StatusConnecting:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case irsh_ssh_engine_ssh.StatusHostKeyCheck:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))

	case irsh_ssh_engine_ssh.StatusReady:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(2))

	case irsh_ssh_engine_ssh.StatusClosed:
		payload := result.Closed()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(3))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_irsh:ssh-engine/ssh#[method]session.status
func wasm_export_post_return_irsh_ssh_engine_ssh_method_session_status(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.host-key-sha256
func wasm_export_irsh_ssh_engine_ssh_method_session_host_key_sha256(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).HostKeySha256()

	switch result.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := result.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_irsh:ssh-engine/ssh#[method]session.host-key-sha256
func wasm_export_post_return_irsh_ssh_engine_ssh_method_session_host_key_sha256(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.host-key-decision
func wasm_export_irsh_ssh_engine_ssh_method_session_host_key_decision(arg0 uintptr, arg1 int32) {

	(export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).HostKeyDecision((arg1 != 0))

}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.write-input
func wasm_export_irsh_ssh_engine_ssh_method_session_write_input(arg0 uintptr, arg1 uintptr, arg2 uint32) {

	value := unsafe.Slice((*uint8)(unsafe.Pointer(arg1)), arg2)
	witRuntime.Unpin()
	(export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).WriteInput(value)

}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.drain-output
func wasm_export_irsh_ssh_engine_ssh_method_session_drain_output(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).DrainOutput()
	data := unsafe.Pointer(unsafe.SliceData(result))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(data)))
	return exportReturnArea

}

//go:wasmexport cabi_post_irsh:ssh-engine/ssh#[method]session.drain-output
func wasm_export_post_return_irsh_ssh_engine_ssh_method_session_drain_output(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.resize
func wasm_export_irsh_ssh_engine_ssh_method_session_resize(arg0 uintptr, arg1 int32, arg2 int32) {

	(export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).Resize(uint16(arg1), uint16(arg2))

}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.exited
func wasm_export_irsh_ssh_engine_ssh_method_session_exited(arg0 uintptr) int32 {

	result := (export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).Exited()
	var result0 int32
	if result {
		result0 = 1
	} else {
		result0 = 0
	}
	return result0

}

//go:wasmexport irsh:ssh-engine/ssh#[method]session.exit-status
func wasm_export_irsh_ssh_engine_ssh_method_session_exit_status(arg0 uintptr) uintptr {

	result := (export_irsh_ssh_engine_ssh.SessionFromBorrowHandle(int32(uintptr(arg0)))).ExitStatus()

	switch result.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := result.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = payload

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

// Unused, but present to make the compiler happy
func main() {}
