// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     experiment:mosh

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/experiment_mosh_ssh"
	"wit_component/export_experiment_mosh_engine"
	"wit_component/export_experiment_mosh_ssh"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 64, 8))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport experiment:mosh/engine#[static]session.connect
func wasm_export_experiment_mosh_engine_static_session_connect(arg0 uintptr, arg1 uint32, arg2 int32, arg3 int32, arg4 int32, arg5 int64) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	var option witTypes.Option[uint64]
	switch arg4 {
	case 0:

		option = witTypes.None[uint64]()
	case 1:

		option = witTypes.Some[uint64](uint64(arg5))
	default:
		panic("unreachable")
	}
	witRuntime.Unpin()
	result := export_experiment_mosh_engine.SessionConnect(value, uint16(arg2), uint16(arg3), option)

	switch result.Tag() {
	case witTypes.ResultOk:
		payload := result.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = (payload).TakeHandle()

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/engine#[static]session.connect
func wasm_export_post_return_experiment_mosh_engine_static_session_connect(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/engine#[method]session.feed-keys
func wasm_export_experiment_mosh_engine_method_session_feed_keys(arg0 uintptr, arg1 uintptr, arg2 uint32) {

	value := unsafe.Slice((*uint8)(unsafe.Pointer(arg1)), arg2)
	witRuntime.Unpin()
	(export_experiment_mosh_engine.SessionFromBorrowHandle(int32(uintptr(arg0)))).FeedKeys(value)

}

//go:wasmexport experiment:mosh/engine#[method]session.resize
func wasm_export_experiment_mosh_engine_method_session_resize(arg0 uintptr, arg1 int32, arg2 int32) {

	(export_experiment_mosh_engine.SessionFromBorrowHandle(int32(uintptr(arg0)))).Resize(uint16(arg1), uint16(arg2))

}

//go:wasmexport experiment:mosh/engine#[method]session.handle-datagram
func wasm_export_experiment_mosh_engine_method_session_handle_datagram(arg0 uintptr, arg1 uintptr, arg2 uint32) {

	value := unsafe.Slice((*uint8)(unsafe.Pointer(arg1)), arg2)
	witRuntime.Unpin()
	(export_experiment_mosh_engine.SessionFromBorrowHandle(int32(uintptr(arg0)))).HandleDatagram(value)

}

//go:wasmexport experiment:mosh/engine#[method]session.tick
func wasm_export_experiment_mosh_engine_method_session_tick(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_experiment_mosh_engine.SessionFromBorrowHandle(int32(uintptr(arg0)))).Tick()
	slice := result
	length := uint32(len(slice))
	result0 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result0, index*(2*4))
		data := unsafe.Pointer(unsafe.SliceData(element))
		pinner.Pin(data)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(data)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(result0)))
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/engine#[method]session.tick
func wasm_export_post_return_experiment_mosh_engine_method_session_tick(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/engine#[method]session.drain-output
func wasm_export_experiment_mosh_engine_method_session_drain_output(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_experiment_mosh_engine.SessionFromBorrowHandle(int32(uintptr(arg0)))).DrainOutput()
	data := unsafe.Pointer(unsafe.SliceData(result))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(data)))
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/engine#[method]session.drain-output
func wasm_export_post_return_experiment_mosh_engine_method_session_drain_output(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/engine#[method]session.stats
func wasm_export_experiment_mosh_engine_method_session_stats(arg0 uintptr) uintptr {

	result := (export_experiment_mosh_engine.SessionFromBorrowHandle(int32(uintptr(arg0)))).Stats()
	*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int64((result).SentNum)
	*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int64((result).AckedNum)
	*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int64((result).RecvNum)

	switch (result).LastRecvAgeMs.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := (result).LastRecvAgeMs.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = int8(int32(1))
		*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 32)) = int64(payload)

	default:
		panic("unreachable")
	}
	*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 40)) = int64((result).RtoMs)
	var result0 int32
	if (result).PredictorActive {
		result0 = 1
	} else {
		result0 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 48)) = int8(result0)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 52)) = int32((result).TrackedStates)
	*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 56)) = int64((result).CurrentSeq)
	return exportReturnArea

}

//go:wasmexport experiment:mosh/engine#version
func wasm_export_experiment_mosh_engine_version() uintptr {

	pinner := &syncExportPinner
	result := export_experiment_mosh_engine.Version()
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/engine#version
func wasm_export_post_return_experiment_mosh_engine_version(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/ssh#[static]ssh-session.connect
func wasm_export_experiment_mosh_ssh_static_ssh_session_connect(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) int32 {

	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	value0 := unsafe.String((*uint8)(unsafe.Pointer(arg2)), arg3)
	witRuntime.Unpin()
	result := export_experiment_mosh_ssh.SshSessionConnect(value, value0)
	return (result).TakeHandle()

}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.feed
func wasm_export_experiment_mosh_ssh_method_ssh_session_feed(arg0 uintptr, arg1 uintptr, arg2 uint32) {

	value := unsafe.Slice((*uint8)(unsafe.Pointer(arg1)), arg2)
	witRuntime.Unpin()
	(export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).Feed(value)

}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.drain
func wasm_export_experiment_mosh_ssh_method_ssh_session_drain(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).Drain()
	data := unsafe.Pointer(unsafe.SliceData(result))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(data)))
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/ssh#[method]ssh-session.drain
func wasm_export_post_return_experiment_mosh_ssh_method_ssh_session_drain(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.pump
func wasm_export_experiment_mosh_ssh_method_ssh_session_pump(arg0 uintptr) {

	(export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).Pump()

}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.status
func wasm_export_experiment_mosh_ssh_method_ssh_session_status(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).Status()

	switch result.Tag() {
	case experiment_mosh_ssh.SshStatusConnecting:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case experiment_mosh_ssh.SshStatusHostKeyCheck:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))

	case experiment_mosh_ssh.SshStatusReady:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(2))

	case experiment_mosh_ssh.SshStatusFailed:
		payload := result.Failed()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(3))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/ssh#[method]ssh-session.status
func wasm_export_post_return_experiment_mosh_ssh_method_ssh_session_status(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.host-key-sha256
func wasm_export_experiment_mosh_ssh_method_ssh_session_host_key_sha256(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).HostKeySha256()

	switch result.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := result.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/ssh#[method]ssh-session.host-key-sha256
func wasm_export_post_return_experiment_mosh_ssh_method_ssh_session_host_key_sha256(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.host-key-decision
func wasm_export_experiment_mosh_ssh_method_ssh_session_host_key_decision(arg0 uintptr, arg1 int32) {

	(export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).HostKeyDecision((arg1 != 0))

}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.exec
func wasm_export_experiment_mosh_ssh_method_ssh_session_exec(arg0 uintptr, arg1 uintptr, arg2 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg1)), arg2)
	witRuntime.Unpin()
	result := (export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).Exec(value)

	switch result.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/ssh#[method]ssh-session.exec
func wasm_export_post_return_experiment_mosh_ssh_method_ssh_session_exec(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.read-output
func wasm_export_experiment_mosh_ssh_method_ssh_session_read_output(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).ReadOutput()
	data := unsafe.Pointer(unsafe.SliceData(result))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(data)))
	return exportReturnArea

}

//go:wasmexport cabi_post_experiment:mosh/ssh#[method]ssh-session.read-output
func wasm_export_post_return_experiment_mosh_ssh_method_ssh_session_read_output(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport experiment:mosh/ssh#[method]ssh-session.exit-status
func wasm_export_experiment_mosh_ssh_method_ssh_session_exit_status(arg0 uintptr) uintptr {

	result := (export_experiment_mosh_ssh.SshSessionFromBorrowHandle(int32(uintptr(arg0)))).ExitStatus()

	switch result.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := result.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = payload

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

// Unused, but present to make the compiler happy
func main() {}
