// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     irsh:ssh-engine
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0

package export_irsh_ssh_engine_ssh

import (
	"unsafe"
)

//go:wasmimport [export]irsh:ssh-engine/ssh [resource-new]session
func resourceNewSession(pointer unsafe.Pointer) int32

//go:wasmimport [export]irsh:ssh-engine/ssh [resource-rep]session
func resourceRepSession(handle int32) unsafe.Pointer

//go:wasmimport [export]irsh:ssh-engine/ssh [resource-drop]session
func resourceDropSession(handle int32)

//go:wasmexport irsh:ssh-engine/ssh#[dtor]session
func resourceDtorSession(rep int32) {
	val := (*Session)(unsafe.Pointer(uintptr(rep)))
	val.handle = 0
	val.pinner.Unpin()
	val.OnDrop()
}

func (self *Session) TakeHandle() int32 {
	self.pinner.Pin(self)
	self.handle = resourceNewSession(unsafe.Pointer(self))
	return self.handle
}

func (self *Session) SetHandle(handle int32) {
	if self.handle != handle {
		panic("invalid handle")
	}
}

func (self *Session) Drop() {
	handle := self.handle
	if self.handle != 0 {
		self.handle = 0
		resourceDropSession(handle)
		self.pinner.Unpin()
		self.OnDrop()
	}
}

func SessionFromOwnHandle(handle int32) *Session {
	return (*Session)(unsafe.Pointer(resourceRepSession(handle)))
}

func SessionFromBorrowHandle(rep int32) *Session {
	return (*Session)(unsafe.Pointer(uintptr(rep)))
}
