// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     irsh:terminal

package polymorph_webcrypto_ed25519_sign

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/polymorph_webcrypto_signature"
	"wit_component/polymorph_webcrypto_types"
	"wit_component/polymorph_webcrypto_wrapping"
)

type Error = polymorph_webcrypto_types.Error
type SigningKey = polymorph_webcrypto_signature.SigningKey
type SigningKeyOptions = polymorph_webcrypto_signature.SigningKeyOptions
type VerifyingKey = polymorph_webcrypto_signature.VerifyingKey
type UnwrapInput = polymorph_webcrypto_wrapping.UnwrapInput

//go:wasmimport polymorph:webcrypto/ed25519-sign@0.1.0 [async-lower]generate-key
func wasm_import_generate_key(arg0 int32, arg1 uintptr) int32

func GenerateKey(options *polymorph_webcrypto_signature.SigningKeyOptions) witTypes.Result[witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey], polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_generate_key((options).TakeHandle(), returnArea)))
	var result witTypes.Result[witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey], polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey], polymorph_webcrypto_types.Error](witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey]{polymorph_webcrypto_signature.SigningKeyFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), polymorph_webcrypto_signature.VerifyingKeyFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 1*4))))))})
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value0)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value1)

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value3)

		case 7:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value4, value5, value6})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Tuple2[*polymorph_webcrypto_signature.SigningKey, *polymorph_webcrypto_signature.VerifyingKey], polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/ed25519-sign@0.1.0 [async-lower]import-signing-key-pkcs8
func wasm_import_import_signing_key_pkcs8(arg0 uintptr, arg1 uint32, arg2 int32, arg3 uintptr) int32

func ImportSigningKeyPkcs8(pkcs8 []uint8, options *polymorph_webcrypto_signature.SigningKeyOptions) witTypes.Result[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))
	data := unsafe.Pointer(unsafe.SliceData(pkcs8))
	pinner.Pin(data)

	witAsync.SubtaskWait(uint32(wasm_import_import_signing_key_pkcs8(uintptr(data), uint32(len(pkcs8)), (options).TakeHandle(), returnArea)))
	var result witTypes.Result[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error](polymorph_webcrypto_signature.SigningKeyFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value0)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value1)

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value3)

		case 7:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value4, value5, value6})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/ed25519-sign@0.1.0 [async-lower]import-signing-key-jwk
func wasm_import_import_signing_key_jwk(arg0 uintptr, arg1 uint32, arg2 int32, arg3 uintptr) int32

func ImportSigningKeyJwk(jwk string, options *polymorph_webcrypto_signature.SigningKeyOptions) witTypes.Result[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(jwk))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_import_signing_key_jwk(uintptr(utf8), uint32(len(jwk)), (options).TakeHandle(), returnArea)))
	var result witTypes.Result[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error](polymorph_webcrypto_signature.SigningKeyFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value0)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value1)

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value3)

		case 7:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value4, value5, value6})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/ed25519-sign@0.1.0 [async-lower]unwrap-signing-key-pkcs8
func wasm_import_unwrap_signing_key_pkcs8(arg0 int32, arg1 int32, arg2 uintptr) int32

func UnwrapSigningKeyPkcs8(input *polymorph_webcrypto_wrapping.UnwrapInput, options *polymorph_webcrypto_signature.SigningKeyOptions) witTypes.Result[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_unwrap_signing_key_pkcs8((input).TakeHandle(), (options).TakeHandle(), returnArea)))
	var result witTypes.Result[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error](polymorph_webcrypto_signature.SigningKeyFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value0)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value1)

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value3)

		case 7:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value4, value5, value6})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/ed25519-sign@0.1.0 [async-lower]unwrap-signing-key-jwk
func wasm_import_unwrap_signing_key_jwk(arg0 int32, arg1 int32, arg2 uintptr) int32

func UnwrapSigningKeyJwk(input *polymorph_webcrypto_wrapping.UnwrapInput, options *polymorph_webcrypto_signature.SigningKeyOptions) witTypes.Result[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_unwrap_signing_key_jwk((input).TakeHandle(), (options).TakeHandle(), returnArea)))
	var result witTypes.Result[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error](polymorph_webcrypto_signature.SigningKeyFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value0)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value1)

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value3)

		case 7:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value4, value5, value6})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*polymorph_webcrypto_signature.SigningKey, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}
