// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     irsh:ssh-engine
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0

package irsh_ssh_engine_ssh

import ()

const (
	StatusConnecting uint8 = 0
	// Parked in the host-key callback: host-key-sha256 is now
	// available and the handshake will not proceed until
	// host-key-decision resolves it. Nothing -- not even a public
	// key probe -- is ever sent to the server before this: x/crypto/ssh
	// authenticates strictly after a successful host-key callback.
	StatusHostKeyCheck uint8 = 1
	// Pty + shell are up; write-input/drain-output carry the
	// interactive session.
	StatusReady uint8 = 2
	// Terminal: the handshake, auth, or shell setup failed, or the
	// connection closed. The string is a human-readable reason.
	StatusClosed uint8 = 3
)

// Where the session currently stands.
type Status struct {
	tag   uint8
	value any
}

func (self Status) Tag() uint8 {
	return self.tag
}

func (self Status) Closed() string {
	if self.tag != StatusClosed {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeStatusConnecting() Status {
	return Status{StatusConnecting, nil}
}
func MakeStatusHostKeyCheck() Status {
	return Status{StatusHostKeyCheck, nil}
}
func MakeStatusReady() Status {
	return Status{StatusReady, nil}
}
func MakeStatusClosed(value string) Status {
	return Status{StatusClosed, value}
}
