// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package polymorph_webcrypto_wrapping

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
)

//go:wasmimport polymorph:webcrypto/wrapping@0.1.0 [resource-drop]wrap-input
func resourceDropWrapInput(handle int32)

// Serialized key material awaiting encryption under a wrapping key.
//
// Constructed by the key resources' `to-wrap-input-*` functions;
// the serialization format chosen there travels with the resource,
// and format-specific wrapping rules (such as `aes-kw`'s JWK
// padding) key on it. Consumed by a wrapping key's `wrap`, on
// failure as on success; construct one per wrap attempt.
type WrapInput struct {
	handle *witRuntime.Handle
}

func (self *WrapInput) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *WrapInput) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *WrapInput) Handle() int32 {
	return self.handle.Use()
}

func (self *WrapInput) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropWrapInput(handle)
	}
}

func WrapInputFromOwnHandle(handleValue int32) *WrapInput {
	handle := witRuntime.MakeHandle(handleValue)
	value := &WrapInput{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropWrapInput(handleValue)
		}
	}, 0)
	return value
}

func WrapInputFromBorrowHandle(handleValue int32) *WrapInput {
	handle := witRuntime.MakeHandle(handleValue)
	return &WrapInput{handle}
}

//go:wasmimport polymorph:webcrypto/wrapping@0.1.0 [resource-drop]unwrap-input
func resourceDropUnwrapInput(handle int32)

// Key material from a wrapped input, awaiting a typed mint.
//
// Produced by a wrapping key's `unwrap`; consumed by one unwrap
// mint (on failure as on success — unwrap again to mint again),
// which declares how the bytes are read (raw, JWK, PKCS#8) the way
// the per-format imports do. The mint need not produce a key: the
// KDF interfaces mint base secrets from it (`hkdf.unwrap-ikm`,
// `pbkdf2.unwrap-password`), a strictly one-way door — no KDF
// secret can produce a `wrap-input`.
//
// Security:
//   - An implementation decrypts — and, for the authenticated
//     wrapping kinds, verifies — at `unwrap`, or defers both to the
//     consuming mint, which then reports the unwrap operation's
//     error cases too. Either way, no mint succeeds on input whose
//     verification fails, and unverified material is never
//     observable.
//   - No grants ride this resource: the minted resource's usages and
//     extractability come from the mint's options alone (the W3C Web
//     Cryptography API's `unwrapKey` model).
type UnwrapInput struct {
	handle *witRuntime.Handle
}

func (self *UnwrapInput) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *UnwrapInput) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *UnwrapInput) Handle() int32 {
	return self.handle.Use()
}

func (self *UnwrapInput) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropUnwrapInput(handle)
	}
}

func UnwrapInputFromOwnHandle(handleValue int32) *UnwrapInput {
	handle := witRuntime.MakeHandle(handleValue)
	value := &UnwrapInput{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropUnwrapInput(handleValue)
		}
	}, 0)
	return value
}

func UnwrapInputFromBorrowHandle(handleValue int32) *UnwrapInput {
	handle := witRuntime.MakeHandle(handleValue)
	return &UnwrapInput{handle}
}
