// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package polymorph_iroh_endpoint

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/polymorph_iroh_identity"
	"wit_component/polymorph_iroh_types"
)

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [stream-new-0][method]send-stream.write-via-stream
func wasm_stream_new_u8() uint64

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][stream-read-0][method]send-stream.write-via-stream
func wasm_stream_read_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][stream-write-0][method]send-stream.write-via-stream
func wasm_stream_write_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [stream-drop-readable-0][method]send-stream.write-via-stream
func wasm_stream_drop_readable_u8(handle int32)

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [stream-drop-writable-0][method]send-stream.write-via-stream
func wasm_stream_drop_writable_u8(handle int32)

var wasm_stream_vtable_u8 = witTypes.StreamVtable[uint8]{
	1,
	1,
	wasm_stream_read_u8,
	wasm_stream_write_u8,
	nil,
	nil,
	wasm_stream_drop_readable_u8,
	wasm_stream_drop_writable_u8,
	nil,
	nil,
}

func MakeStreamU8() (*witTypes.StreamWriter[uint8], *witTypes.StreamReader[uint8]) {
	pair := wasm_stream_new_u8()
	return witTypes.MakeStreamWriter[uint8](&wasm_stream_vtable_u8, int32(pair>>32)),
		witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, int32(pair&0xFFFFFFFF))
}

func LiftStreamU8(handle int32) *witTypes.StreamReader[uint8] {
	return witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, handle)
}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [future-new-1][method]recv-stream.read-via-stream
func wasm_future_new_result_unit_polymorph_iroh_types_error() uint64

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][future-read-1][method]recv-stream.read-via-stream
func wasm_future_read_result_unit_polymorph_iroh_types_error(handle int32, item unsafe.Pointer) uint32

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][future-write-1][method]recv-stream.read-via-stream
func wasm_future_write_result_unit_polymorph_iroh_types_error(handle int32, item unsafe.Pointer) uint32

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [future-drop-readable-1][method]recv-stream.read-via-stream
func wasm_future_drop_readable_result_unit_polymorph_iroh_types_error(handle int32)

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [future-drop-writable-1][method]recv-stream.read-via-stream
func wasm_future_drop_writable_result_unit_polymorph_iroh_types_error(handle int32)

func wasm_future_lift_result_unit_polymorph_iroh_types_error(src unsafe.Pointer) witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error] {
	var result witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, polymorph_iroh_types.Error](witTypes.Unit{})
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(src), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result
}

func wasm_future_lower_result_unit_polymorph_iroh_types_error(
	pinner *runtime.Pinner,
	value witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error],
	dst unsafe.Pointer,
) func() {

	switch value.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := value.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(1))

		switch payload.Tag() {
		case polymorph_iroh_types.ErrorClosed:

			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 8)) = int8(int32(0))

		case polymorph_iroh_types.ErrorReset:
			payload := payload.Reset()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 8)) = int8(int32(1))
			*(*int64)(unsafe.Add(unsafe.Pointer(dst), 16)) = int64(payload)

		case polymorph_iroh_types.ErrorConnectFailed:
			payload := payload.ConnectFailed()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 8)) = int8(int32(2))
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (16 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 16)) = uint32(uintptr(uintptr(utf8)))

		case polymorph_iroh_types.ErrorInvalidArgument:
			payload := payload.InvalidArgument()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 8)) = int8(int32(3))
			utf82 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf82)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (16 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 16)) = uint32(uintptr(uintptr(utf82)))

		case polymorph_iroh_types.ErrorOther:
			payload := payload.Other()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 8)) = int8(int32(4))
			utf83 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf83)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (16 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 16)) = uint32(uintptr(uintptr(utf83)))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}

	return func() {}
}

var wasm_future_vtable_result_unit_polymorph_iroh_types_error = witTypes.FutureVtable[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]]{
	(16 + 2*4),
	8,
	wasm_future_read_result_unit_polymorph_iroh_types_error,
	wasm_future_write_result_unit_polymorph_iroh_types_error,
	nil,
	nil,
	wasm_future_drop_readable_result_unit_polymorph_iroh_types_error,
	wasm_future_drop_writable_result_unit_polymorph_iroh_types_error,
	wasm_future_lift_result_unit_polymorph_iroh_types_error,
	wasm_future_lower_result_unit_polymorph_iroh_types_error,
}

func MakeFutureResultUnitPolymorphIrohTypesError() (*witTypes.FutureWriter[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]]) {
	pair := wasm_future_new_result_unit_polymorph_iroh_types_error()
	return witTypes.MakeFutureWriter[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]](&wasm_future_vtable_result_unit_polymorph_iroh_types_error, int32(pair>>32)),
		witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]](&wasm_future_vtable_result_unit_polymorph_iroh_types_error, int32(pair&0xFFFFFFFF))
}

func LiftFutureResultUnitPolymorphIrohTypesError(handle int32) *witTypes.FutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]] {
	return witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]](&wasm_future_vtable_result_unit_polymorph_iroh_types_error, handle)
}

type EndpointId = []uint8
type EndpointAddr = polymorph_iroh_types.EndpointAddr
type ConnectionState = polymorph_iroh_types.ConnectionState
type CloseInfo = polymorph_iroh_types.CloseInfo
type PathKind = polymorph_iroh_types.PathKind
type Error = polymorph_iroh_types.Error
type Identity = polymorph_iroh_identity.Identity

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [resource-drop]endpoint-options
func resourceDropEndpointOptions(handle int32)

// Configuration for `endpoint.bind`: constructed around the
// endpoint's identity — the one mandatory input — then populated
// through the setters. Every setting starts disabled or unset.
type EndpointOptions struct {
	handle *witRuntime.Handle
}

func (self *EndpointOptions) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *EndpointOptions) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *EndpointOptions) Handle() int32 {
	return self.handle.Use()
}

func (self *EndpointOptions) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropEndpointOptions(handle)
	}
}

func EndpointOptionsFromOwnHandle(handleValue int32) *EndpointOptions {
	handle := witRuntime.MakeHandle(handleValue)
	value := &EndpointOptions{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropEndpointOptions(handleValue)
		}
	}, 0)
	return value
}

func EndpointOptionsFromBorrowHandle(handleValue int32) *EndpointOptions {
	handle := witRuntime.MakeHandle(handleValue)
	return &EndpointOptions{handle}
}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [resource-drop]endpoint
func resourceDropEndpoint(handle int32)

// A bound endpoint: an identity plus the machinery to connect and
// accept.
type Endpoint struct {
	handle *witRuntime.Handle
}

func (self *Endpoint) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Endpoint) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Endpoint) Handle() int32 {
	return self.handle.Use()
}

func (self *Endpoint) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropEndpoint(handle)
	}
}

func EndpointFromOwnHandle(handleValue int32) *Endpoint {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Endpoint{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropEndpoint(handleValue)
		}
	}, 0)
	return value
}

func EndpointFromBorrowHandle(handleValue int32) *Endpoint {
	handle := witRuntime.MakeHandle(handleValue)
	return &Endpoint{handle}
}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [resource-drop]connection
func resourceDropConnection(handle int32)

// An authenticated QUIC connection to one peer.
type Connection struct {
	handle *witRuntime.Handle
}

func (self *Connection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
	return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Connection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConnection(handleValue)
		}
	}, 0)
	return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	return &Connection{handle}
}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [resource-drop]send-stream
func resourceDropSendStream(handle int32)

// The send half of a QUIC stream.
type SendStream struct {
	handle *witRuntime.Handle
}

func (self *SendStream) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *SendStream) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *SendStream) Handle() int32 {
	return self.handle.Use()
}

func (self *SendStream) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropSendStream(handle)
	}
}

func SendStreamFromOwnHandle(handleValue int32) *SendStream {
	handle := witRuntime.MakeHandle(handleValue)
	value := &SendStream{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropSendStream(handleValue)
		}
	}, 0)
	return value
}

func SendStreamFromBorrowHandle(handleValue int32) *SendStream {
	handle := witRuntime.MakeHandle(handleValue)
	return &SendStream{handle}
}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [resource-drop]recv-stream
func resourceDropRecvStream(handle int32)

// The receive half of a QUIC stream.
type RecvStream struct {
	handle *witRuntime.Handle
}

func (self *RecvStream) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *RecvStream) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *RecvStream) Handle() int32 {
	return self.handle.Use()
}

func (self *RecvStream) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropRecvStream(handle)
	}
}

func RecvStreamFromOwnHandle(handleValue int32) *RecvStream {
	handle := witRuntime.MakeHandle(handleValue)
	value := &RecvStream{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropRecvStream(handleValue)
		}
	}, 0)
	return value
}

func RecvStreamFromBorrowHandle(handleValue int32) *RecvStream {
	handle := witRuntime.MakeHandle(handleValue)
	return &RecvStream{handle}
}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [constructor]endpoint-options
func wasm_import_constructor_endpoint_options(arg0 int32) int32

func MakeEndpointOptions(identity *polymorph_iroh_identity.Identity) *EndpointOptions {

	result := wasm_import_constructor_endpoint_options((identity).Handle())
	return EndpointOptionsFromOwnHandle(int32(uintptr(result)))

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]endpoint-options.add-alpn
func wasm_import_method_endpoint_options_add_alpn(arg0 int32, arg1 uintptr, arg2 uint32)

func (self *EndpointOptions) AddAlpn(alpn []uint8) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	data := unsafe.Pointer(unsafe.SliceData(alpn))
	pinner.Pin(data)
	wasm_import_method_endpoint_options_add_alpn((self).Handle(), uintptr(data), uint32(len(alpn)))

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]endpoint-options.relay-url
func wasm_import_method_endpoint_options_relay_url(arg0 int32, arg1 uintptr, arg2 uint32)

func (self *EndpointOptions) RelayUrl(url string) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(url))
	pinner.Pin(utf8)
	wasm_import_method_endpoint_options_relay_url((self).Handle(), uintptr(utf8), uint32(len(url)))

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]endpoint-options.udp-bind-addr
func wasm_import_method_endpoint_options_udp_bind_addr(arg0 int32, arg1 uintptr, arg2 uint32)

func (self *EndpointOptions) UdpBindAddr(addr string) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(addr))
	pinner.Pin(utf8)
	wasm_import_method_endpoint_options_udp_bind_addr((self).Handle(), uintptr(utf8), uint32(len(addr)))

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]endpoint-options.webrtc
func wasm_import_method_endpoint_options_webrtc(arg0 int32, arg1 int32)

func (self *EndpointOptions) Webrtc(enabled bool) {

	var result int32
	if enabled {
		result = 1
	} else {
		result = 0
	}
	wasm_import_method_endpoint_options_webrtc((self).Handle(), result)

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][static]endpoint.bind
func wasm_import_static_endpoint_bind(arg0 int32, arg1 uintptr) int32

func EndpointBind(options *EndpointOptions) witTypes.Result[*Endpoint, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_static_endpoint_bind((options).TakeHandle(), returnArea)))
	var result witTypes.Result[*Endpoint, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Endpoint, polymorph_iroh_types.Error](EndpointFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Endpoint, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]endpoint.id
func wasm_import_method_endpoint_id(arg0 int32, arg1 uintptr)

func (self *Endpoint) Id() []uint8 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_endpoint_id((self).Handle(), returnArea)
	value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]endpoint.direct-addr
func wasm_import_method_endpoint_direct_addr(arg0 int32, arg1 uintptr)

func (self *Endpoint) DirectAddr() witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_endpoint_direct_addr((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]endpoint.connect
func wasm_import_method_endpoint_connect(arg0 uintptr, arg1 uintptr) int32

func (self *Endpoint) Connect(addr polymorph_iroh_types.EndpointAddr, alpn []uint8) witTypes.Result[*Connection, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	params := witRuntime.Allocate(pinner, (7 * 4), 4)
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = (self).Handle()
	data := unsafe.Pointer(unsafe.SliceData((addr).EndpointId))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = uint32(uint32(len((addr).EndpointId)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = uint32(uintptr(uintptr(data)))
	slice := (addr).Addrs
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(16+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result, index*(16+2*4))

		switch element.Tag() {
		case polymorph_iroh_types.TransportAddrRelay:
			payload := element.Relay()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8)))

		case polymorph_iroh_types.TransportAddrIp:
			payload := element.Ip()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case polymorph_iroh_types.TransportAddrWebrtc:
			payload := element.Webrtc()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			utf81 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf81)))

		case polymorph_iroh_types.TransportAddrCustom:
			payload := element.Custom()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((payload).Id)
			data2 := unsafe.Pointer(unsafe.SliceData((payload).Data))
			pinner.Pin(data2)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 1*4))) = uint32(uint32(len((payload).Data)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16)) = uint32(uintptr(uintptr(data2)))

		default:
			panic("unreachable")
		}

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), (3 * 4))) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), (2 * 4))) = uint32(uintptr(uintptr(result)))
	data3 := unsafe.Pointer(unsafe.SliceData(alpn))
	pinner.Pin(data3)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (5*4))), 4)) = uint32(uint32(len(alpn)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (5*4))), 0)) = uint32(uintptr(uintptr(data3)))

	witAsync.SubtaskWait(uint32(wasm_import_method_endpoint_connect(uintptr(params), returnArea)))
	var result6 witTypes.Result[*Connection, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result6 = witTypes.Ok[*Connection, polymorph_iroh_types.Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value4)

		case 4:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value5)

		default:
			panic("unreachable")
		}

		result6 = witTypes.Err[*Connection, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result6

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]endpoint.accept
func wasm_import_method_endpoint_accept(arg0 int32, arg1 uintptr) int32

func (self *Endpoint) Accept() witTypes.Result[*Connection, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_endpoint_accept((self).Handle(), returnArea)))
	var result witTypes.Result[*Connection, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Connection, polymorph_iroh_types.Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Connection, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]endpoint.close
func wasm_import_method_endpoint_close(arg0 int32)

func (self *Endpoint) Close() {

	wasm_import_method_endpoint_close((self).Handle())

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]connection.peer
func wasm_import_method_connection_peer(arg0 int32, arg1 uintptr)

func (self *Connection) Peer() []uint8 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_connection_peer((self).Handle(), returnArea)
	value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]connection.alpn
func wasm_import_method_connection_alpn(arg0 int32, arg1 uintptr)

func (self *Connection) Alpn() []uint8 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_connection_alpn((self).Handle(), returnArea)
	value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]connection.state
func wasm_import_method_connection_state(arg0 int32) int32

func (self *Connection) State() polymorph_iroh_types.ConnectionState {

	result := wasm_import_method_connection_state((self).Handle())
	return uint8(result)

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]connection.path
func wasm_import_method_connection_path(arg0 int32) int32

func (self *Connection) Path() polymorph_iroh_types.PathKind {

	result := wasm_import_method_connection_path((self).Handle())
	return uint8(result)

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]connection.open-bi
func wasm_import_method_connection_open_bi(arg0 int32, arg1 uintptr) int32

func (self *Connection) OpenBi() witTypes.Result[witTypes.Tuple2[*SendStream, *RecvStream], polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_open_bi((self).Handle(), returnArea)))
	var result witTypes.Result[witTypes.Tuple2[*SendStream, *RecvStream], polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Tuple2[*SendStream, *RecvStream], polymorph_iroh_types.Error](witTypes.Tuple2[*SendStream, *RecvStream]{SendStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), RecvStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12)))))})
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Tuple2[*SendStream, *RecvStream], polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]connection.open-uni
func wasm_import_method_connection_open_uni(arg0 int32, arg1 uintptr) int32

func (self *Connection) OpenUni() witTypes.Result[*SendStream, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_open_uni((self).Handle(), returnArea)))
	var result witTypes.Result[*SendStream, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*SendStream, polymorph_iroh_types.Error](SendStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*SendStream, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]connection.accept-bi
func wasm_import_method_connection_accept_bi(arg0 int32, arg1 uintptr) int32

func (self *Connection) AcceptBi() witTypes.Result[witTypes.Tuple2[*SendStream, *RecvStream], polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_accept_bi((self).Handle(), returnArea)))
	var result witTypes.Result[witTypes.Tuple2[*SendStream, *RecvStream], polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Tuple2[*SendStream, *RecvStream], polymorph_iroh_types.Error](witTypes.Tuple2[*SendStream, *RecvStream]{SendStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), RecvStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12)))))})
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Tuple2[*SendStream, *RecvStream], polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]connection.accept-uni
func wasm_import_method_connection_accept_uni(arg0 int32, arg1 uintptr) int32

func (self *Connection) AcceptUni() witTypes.Result[*RecvStream, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_accept_uni((self).Handle(), returnArea)))
	var result witTypes.Result[*RecvStream, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*RecvStream, polymorph_iroh_types.Error](RecvStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*RecvStream, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]connection.max-datagram-size
func wasm_import_method_connection_max_datagram_size(arg0 int32, arg1 uintptr)

func (self *Connection) MaxDatagramSize() witTypes.Option[uint32] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_method_connection_max_datagram_size((self).Handle(), returnArea)
	var option witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[uint32]()
	case 1:

		option = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]connection.send-datagram
func wasm_import_method_connection_send_datagram(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Connection) SendDatagram(data []uint8) witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	data0 := unsafe.Pointer(unsafe.SliceData(data))
	pinner.Pin(data0)
	wasm_import_method_connection_send_datagram((self).Handle(), uintptr(data0), uint32(len(data)), returnArea)
	var result witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, polymorph_iroh_types.Error](witTypes.Unit{})
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value1)

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value2)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}
	result3 := result
	return result3

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]connection.recv-datagram
func wasm_import_method_connection_recv_datagram(arg0 int32, arg1 uintptr) int32

func (self *Connection) RecvDatagram() witTypes.Result[[]uint8, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_recv_datagram((self).Handle(), returnArea)))
	var result witTypes.Result[[]uint8, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))

		result = witTypes.Ok[[]uint8, polymorph_iroh_types.Error](value)
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value0)

		case 3:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value1)

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value2)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[[]uint8, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]connection.close
func wasm_import_method_connection_close(arg0 int32, arg1 int64, arg2 uintptr, arg3 uint32)

func (self *Connection) Close(code uint64, reason string) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(reason))
	pinner.Pin(utf8)
	wasm_import_method_connection_close((self).Handle(), int64(code), uintptr(utf8), uint32(len(reason)))

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]connection.wait-closed
func wasm_import_method_connection_wait_closed(arg0 int32, arg1 uintptr) int32

func (self *Connection) WaitClosed() witTypes.Option[polymorph_iroh_types.CloseInfo] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_wait_closed((self).Handle(), returnArea)))
	var option witTypes.Option[polymorph_iroh_types.CloseInfo]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[polymorph_iroh_types.CloseInfo]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

		option = witTypes.Some[polymorph_iroh_types.CloseInfo](polymorph_iroh_types.CloseInfo{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))), value})
	default:
		panic("unreachable")
	}

	return option

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]send-stream.write
func wasm_import_method_send_stream_write(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *SendStream) Write(bytes []uint8) witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	data := unsafe.Pointer(unsafe.SliceData(bytes))
	pinner.Pin(data)

	witAsync.SubtaskWait(uint32(wasm_import_method_send_stream_write((self).Handle(), uintptr(data), uint32(len(bytes)), returnArea)))
	var result witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, polymorph_iroh_types.Error](witTypes.Unit{})
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]send-stream.finish
func wasm_import_method_send_stream_finish(arg0 int32, arg1 uintptr)

func (self *SendStream) Finish() witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	wasm_import_method_send_stream_finish((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, polymorph_iroh_types.Error](witTypes.Unit{})
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}
	result2 := result
	return result2

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]send-stream.reset
func wasm_import_method_send_stream_reset(arg0 int32, arg1 int64)

func (self *SendStream) Reset(code uint64) {

	wasm_import_method_send_stream_reset((self).Handle(), int64(code))

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]send-stream.write-via-stream
func wasm_import_method_send_stream_write_via_stream(arg0 int32, arg1 int32, arg2 uintptr) int32

func (self *SendStream) WriteViaStream(data *witTypes.StreamReader[uint8]) witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_send_stream_write_via_stream((self).Handle(), (data).TakeHandle(), returnArea)))
	var result witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, polymorph_iroh_types.Error](witTypes.Unit{})
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [async-lower][method]recv-stream.read
func wasm_import_method_recv_stream_read(arg0 int32, arg1 int32, arg2 uintptr) int32

func (self *RecvStream) Read(max uint32) witTypes.Result[witTypes.Option[[]uint8], polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_recv_stream_read((self).Handle(), int32(max), returnArea)))
	var result witTypes.Result[witTypes.Option[[]uint8], polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[[]uint8]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			option = witTypes.None[[]uint8]()
		case 1:
			value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			option = witTypes.Some[[]uint8](value)
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[witTypes.Option[[]uint8], polymorph_iroh_types.Error](option)
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value0)

		case 3:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value1)

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value2)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Option[[]uint8], polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]recv-stream.stop
func wasm_import_method_recv_stream_stop(arg0 int32, arg1 int64)

func (self *RecvStream) Stop(code uint64) {

	wasm_import_method_recv_stream_stop((self).Handle(), int64(code))

}

//go:wasmimport polymorph:iroh/endpoint@0.1.0 [method]recv-stream.read-via-stream
func wasm_import_method_recv_stream_read_via_stream(arg0 int32, arg1 uintptr)

func (self *RecvStream) ReadViaStream() witTypes.Result[witTypes.Tuple2[*witTypes.StreamReader[uint8], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]]], polymorph_iroh_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	wasm_import_method_recv_stream_read_via_stream((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Tuple2[*witTypes.StreamReader[uint8], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]]], polymorph_iroh_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Tuple2[*witTypes.StreamReader[uint8], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]]], polymorph_iroh_types.Error](witTypes.Tuple2[*witTypes.StreamReader[uint8], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]]]{LiftStreamU8(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))), LiftFutureResultUnitPolymorphIrohTypesError(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12)))})
	case 1:
		var variant polymorph_iroh_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = polymorph_iroh_types.MakeErrorClosed()

		case 1:

			variant = polymorph_iroh_types.MakeErrorReset(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorConnectFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorInvalidArgument(value0)

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = polymorph_iroh_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Tuple2[*witTypes.StreamReader[uint8], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, polymorph_iroh_types.Error]]], polymorph_iroh_types.Error](variant)
	default:
		panic("unreachable")
	}
	result2 := result
	return result2

}
