// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:clocks@0.3.0
//     spike:goasync

package main

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
	"wit_component/export_spike_goasync_probe"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (2 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport spike:goasync/probe#sync-calls-async
func wasm_export_spike_goasync_probe_sync_calls_async(arg0 int64) uintptr {

	pinner := &syncExportPinner
	result := export_spike_goasync_probe.SyncCallsAsync(uint64(arg0))
	utf8 := unsafe.Pointer(unsafe.StringData(result))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	return exportReturnArea

}

//go:wasmexport cabi_post_spike:goasync/probe#sync-calls-async
func wasm_export_post_return_spike_goasync_probe_sync_calls_async(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport [async-lift]spike:goasync/probe#async-calls-async
func wasm_export_spike_goasync_probe_async_calls_async(arg0 int64) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := export_spike_goasync_probe.AsyncCallsAsync(uint64(arg0))
		utf8 := unsafe.Pointer(unsafe.StringData(result))
		pinner.Pin(utf8)
		wasm_export_task_return_spike_goasync_probe_async_calls_async(uintptr(utf8), uint32(len(result)))

	}))
}

//go:wasmexport [callback][async-lift]spike:goasync/probe#async-calls-async
func wasm_export_callback_spike_goasync_probe_async_calls_async(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]spike:goasync/probe [task-return]async-calls-async
func wasm_export_task_return_spike_goasync_probe_async_calls_async(arg0 uintptr, arg1 uint32)

//go:wasmexport [async-lift]spike:goasync/probe#park
func wasm_export_spike_goasync_probe_park() int32 {
	return int32(witAsync.Run(func() {

		export_spike_goasync_probe.Park()
		wasm_export_task_return_spike_goasync_probe_park()

	}))
}

//go:wasmexport [callback][async-lift]spike:goasync/probe#park
func wasm_export_callback_spike_goasync_probe_park(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]spike:goasync/probe [task-return]park
func wasm_export_task_return_spike_goasync_probe_park()

//go:wasmexport [async-lift]spike:goasync/probe#release
func wasm_export_spike_goasync_probe_release(arg0 int64) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := export_spike_goasync_probe.Release(uint64(arg0))
		utf8 := unsafe.Pointer(unsafe.StringData(result))
		pinner.Pin(utf8)
		wasm_export_task_return_spike_goasync_probe_release(uintptr(utf8), uint32(len(result)))

	}))
}

//go:wasmexport [callback][async-lift]spike:goasync/probe#release
func wasm_export_callback_spike_goasync_probe_release(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]spike:goasync/probe [task-return]release
func wasm_export_task_return_spike_goasync_probe_release(arg0 uintptr, arg1 uint32)

//go:wasmexport [async-lift]spike:goasync/probe#keepalive
func wasm_export_spike_goasync_probe_keepalive() int32 {
	return int32(witAsync.Run(func() {

		export_spike_goasync_probe.Keepalive()
		wasm_export_task_return_spike_goasync_probe_keepalive()

	}))
}

//go:wasmexport [callback][async-lift]spike:goasync/probe#keepalive
func wasm_export_callback_spike_goasync_probe_keepalive(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]spike:goasync/probe [task-return]keepalive
func wasm_export_task_return_spike_goasync_probe_keepalive()

//go:wasmexport [async-lift]spike:goasync/probe#start-bg
func wasm_export_spike_goasync_probe_start_bg() int32 {
	return int32(witAsync.Run(func() {

		export_spike_goasync_probe.StartBg()
		wasm_export_task_return_spike_goasync_probe_start_bg()

	}))
}

//go:wasmexport [callback][async-lift]spike:goasync/probe#start-bg
func wasm_export_callback_spike_goasync_probe_start_bg(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]spike:goasync/probe [task-return]start-bg
func wasm_export_task_return_spike_goasync_probe_start_bg()

//go:wasmexport [async-lift]spike:goasync/probe#bg-count
func wasm_export_spike_goasync_probe_bg_count() int32 {
	return int32(witAsync.Run(func() {

		result := export_spike_goasync_probe.BgCount()
		wasm_export_task_return_spike_goasync_probe_bg_count(int64(result))

	}))
}

//go:wasmexport [callback][async-lift]spike:goasync/probe#bg-count
func wasm_export_callback_spike_goasync_probe_bg_count(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]spike:goasync/probe [task-return]bg-count
func wasm_export_task_return_spike_goasync_probe_bg_count(arg0 int64)

// Unused, but present to make the compiler happy
func main() {}
