// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     irsh:terminal

package polymorph_webcrypto_signature

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/polymorph_webcrypto_types"
	"wit_component/polymorph_webcrypto_wrapping"
)

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [stream-new-0][method]verifying-key.verify
func wasm_stream_new_u8() uint64

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][stream-read-0][method]verifying-key.verify
func wasm_stream_read_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][stream-write-0][method]verifying-key.verify
func wasm_stream_write_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [stream-drop-readable-0][method]verifying-key.verify
func wasm_stream_drop_readable_u8(handle int32)

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [stream-drop-writable-0][method]verifying-key.verify
func wasm_stream_drop_writable_u8(handle int32)

var wasm_stream_vtable_u8 = witTypes.StreamVtable[uint8]{
	1,
	1,
	wasm_stream_read_u8,
	wasm_stream_write_u8,
	nil,
	nil,
	wasm_stream_drop_readable_u8,
	wasm_stream_drop_writable_u8,
	nil,
	nil,
}

func MakeStreamU8() (*witTypes.StreamWriter[uint8], *witTypes.StreamReader[uint8]) {
	pair := wasm_stream_new_u8()
	return witTypes.MakeStreamWriter[uint8](&wasm_stream_vtable_u8, int32(pair>>32)),
		witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, int32(pair&0xFFFFFFFF))
}

func LiftStreamU8(handle int32) *witTypes.StreamReader[uint8] {
	return witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, handle)
}

type Error = polymorph_webcrypto_types.Error
type WrapInput = polymorph_webcrypto_wrapping.WrapInput

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [resource-drop]signing-key-options
func resourceDropSigningKeyOptions(handle int32)

// Mint-time policy for a `signing-key`. Grants nothing by default;
// see `README.md`, "Key-options contract". `can-sign` is the sole
// usage today (the public/private resource split already separates
// sign from verify structurally); the resource carries `extractable`
// and receives future private-key usages additively.
type SigningKeyOptions struct {
	handle *witRuntime.Handle
}

func (self *SigningKeyOptions) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *SigningKeyOptions) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *SigningKeyOptions) Handle() int32 {
	return self.handle.Use()
}

func (self *SigningKeyOptions) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropSigningKeyOptions(handle)
	}
}

func SigningKeyOptionsFromOwnHandle(handleValue int32) *SigningKeyOptions {
	handle := witRuntime.MakeHandle(handleValue)
	value := &SigningKeyOptions{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropSigningKeyOptions(handleValue)
		}
	}, 0)
	return value
}

func SigningKeyOptionsFromBorrowHandle(handleValue int32) *SigningKeyOptions {
	handle := witRuntime.MakeHandle(handleValue)
	return &SigningKeyOptions{handle}
}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [resource-drop]verifying-key
func resourceDropVerifyingKey(handle int32)

// A public key: verification only, secret-free.
type VerifyingKey struct {
	handle *witRuntime.Handle
}

func (self *VerifyingKey) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *VerifyingKey) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *VerifyingKey) Handle() int32 {
	return self.handle.Use()
}

func (self *VerifyingKey) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropVerifyingKey(handle)
	}
}

func VerifyingKeyFromOwnHandle(handleValue int32) *VerifyingKey {
	handle := witRuntime.MakeHandle(handleValue)
	value := &VerifyingKey{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropVerifyingKey(handleValue)
		}
	}, 0)
	return value
}

func VerifyingKeyFromBorrowHandle(handleValue int32) *VerifyingKey {
	handle := witRuntime.MakeHandle(handleValue)
	return &VerifyingKey{handle}
}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [resource-drop]signing-key
func resourceDropSigningKey(handle int32)

// A private key. `sign` is one-shot on the immutable key, mirroring
// `mac-key.sign`. The extractability contract in `README.md` applies.
type SigningKey struct {
	handle *witRuntime.Handle
}

func (self *SigningKey) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *SigningKey) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *SigningKey) Handle() int32 {
	return self.handle.Use()
}

func (self *SigningKey) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropSigningKey(handle)
	}
}

func SigningKeyFromOwnHandle(handleValue int32) *SigningKey {
	handle := witRuntime.MakeHandle(handleValue)
	value := &SigningKey{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropSigningKey(handleValue)
		}
	}, 0)
	return value
}

func SigningKeyFromBorrowHandle(handleValue int32) *SigningKey {
	handle := witRuntime.MakeHandle(handleValue)
	return &SigningKey{handle}
}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [constructor]signing-key-options
func wasm_import_constructor_signing_key_options() int32

func MakeSigningKeyOptions() *SigningKeyOptions {

	result := wasm_import_constructor_signing_key_options()
	return SigningKeyOptionsFromOwnHandle(int32(uintptr(result)))

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key-options.can-sign
func wasm_import_method_signing_key_options_can_sign(arg0 int32, arg1 int32)

func (self *SigningKeyOptions) CanSign(allowed bool) {

	var result int32
	if allowed {
		result = 1
	} else {
		result = 0
	}
	wasm_import_method_signing_key_options_can_sign((self).Handle(), result)

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key-options.extractable
func wasm_import_method_signing_key_options_extractable(arg0 int32, arg1 int32)

func (self *SigningKeyOptions) Extractable(allowed bool) {

	var result int32
	if allowed {
		result = 1
	} else {
		result = 0
	}
	wasm_import_method_signing_key_options_extractable((self).Handle(), result)

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]verifying-key.verify
func wasm_import_method_verifying_key_verify(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32, arg4 uintptr) int32

func (self *VerifyingKey) Verify(data *witTypes.StreamReader[uint8], sig []uint8) witTypes.Result[witTypes.Unit, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))
	data0 := unsafe.Pointer(unsafe.SliceData(sig))
	pinner.Pin(data0)

	witAsync.SubtaskWait(uint32(wasm_import_method_verifying_key_verify((self).Handle(), (data).TakeHandle(), uintptr(data0), uint32(len(sig)), returnArea)))
	var result witTypes.Result[witTypes.Unit, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, polymorph_webcrypto_types.Error](witTypes.Unit{})
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value1)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value2)

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value4)

		case 7:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value5, value6, value7})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]verifying-key.algorithm-name
func wasm_import_method_verifying_key_algorithm_name(arg0 int32, arg1 uintptr)

func (self *VerifyingKey) AlgorithmName() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_verifying_key_algorithm_name((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]verifying-key.algorithm-curve
func wasm_import_method_verifying_key_algorithm_curve(arg0 int32, arg1 uintptr)

func (self *VerifyingKey) AlgorithmCurve() witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_verifying_key_algorithm_curve((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]verifying-key.algorithm-hash
func wasm_import_method_verifying_key_algorithm_hash(arg0 int32, arg1 uintptr)

func (self *VerifyingKey) AlgorithmHash() witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_verifying_key_algorithm_hash((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]verifying-key.algorithm-length
func wasm_import_method_verifying_key_algorithm_length(arg0 int32, arg1 uintptr)

func (self *VerifyingKey) AlgorithmLength() witTypes.Option[uint32] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_method_verifying_key_algorithm_length((self).Handle(), returnArea)
	var option witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[uint32]()
	case 1:

		option = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]verifying-key.algorithm-public-exponent
func wasm_import_method_verifying_key_algorithm_public_exponent(arg0 int32, arg1 uintptr)

func (self *VerifyingKey) AlgorithmPublicExponent() witTypes.Option[[]uint8] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_verifying_key_algorithm_public_exponent((self).Handle(), returnArea)
	var option witTypes.Option[[]uint8]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[[]uint8]()
	case 1:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[[]uint8](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]verifying-key.export-key-raw
func wasm_import_method_verifying_key_export_key_raw(arg0 int32, arg1 uintptr) int32

func (self *VerifyingKey) ExportKeyRaw() witTypes.Result[[]uint8, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_verifying_key_export_key_raw((self).Handle(), returnArea)))
	var result witTypes.Result[[]uint8, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, polymorph_webcrypto_types.Error](value)
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value1)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value2)

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value4)

		case 7:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value5, value6, value7})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[[]uint8, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]verifying-key.export-key-spki
func wasm_import_method_verifying_key_export_key_spki(arg0 int32, arg1 uintptr) int32

func (self *VerifyingKey) ExportKeySpki() witTypes.Result[[]uint8, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_verifying_key_export_key_spki((self).Handle(), returnArea)))
	var result witTypes.Result[[]uint8, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, polymorph_webcrypto_types.Error](value)
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value1)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value2)

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value4)

		case 7:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value5, value6, value7})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[[]uint8, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]verifying-key.export-key-jwk
func wasm_import_method_verifying_key_export_key_jwk(arg0 int32, arg1 uintptr) int32

func (self *VerifyingKey) ExportKeyJwk() witTypes.Result[string, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_verifying_key_export_key_jwk((self).Handle(), returnArea)))
	var result witTypes.Result[string, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[string, polymorph_webcrypto_types.Error](value)
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value1)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value2)

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value4)

		case 7:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value5, value6, value7})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[string, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]signing-key.sign
func wasm_import_method_signing_key_sign(arg0 int32, arg1 int32, arg2 uintptr) int32

func (self *SigningKey) Sign(data *witTypes.StreamReader[uint8]) witTypes.Result[[]uint8, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_signing_key_sign((self).Handle(), (data).TakeHandle(), returnArea)))
	var result witTypes.Result[[]uint8, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, polymorph_webcrypto_types.Error](value)
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value1)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value2)

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value4)

		case 7:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value5, value6, value7})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[[]uint8, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key.algorithm-name
func wasm_import_method_signing_key_algorithm_name(arg0 int32, arg1 uintptr)

func (self *SigningKey) AlgorithmName() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_signing_key_algorithm_name((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key.algorithm-curve
func wasm_import_method_signing_key_algorithm_curve(arg0 int32, arg1 uintptr)

func (self *SigningKey) AlgorithmCurve() witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_signing_key_algorithm_curve((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key.algorithm-hash
func wasm_import_method_signing_key_algorithm_hash(arg0 int32, arg1 uintptr)

func (self *SigningKey) AlgorithmHash() witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_signing_key_algorithm_hash((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key.algorithm-length
func wasm_import_method_signing_key_algorithm_length(arg0 int32, arg1 uintptr)

func (self *SigningKey) AlgorithmLength() witTypes.Option[uint32] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_method_signing_key_algorithm_length((self).Handle(), returnArea)
	var option witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[uint32]()
	case 1:

		option = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key.algorithm-public-exponent
func wasm_import_method_signing_key_algorithm_public_exponent(arg0 int32, arg1 uintptr)

func (self *SigningKey) AlgorithmPublicExponent() witTypes.Option[[]uint8] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_signing_key_algorithm_public_exponent((self).Handle(), returnArea)
	var option witTypes.Option[[]uint8]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[[]uint8]()
	case 1:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[[]uint8](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key.extractable
func wasm_import_method_signing_key_extractable(arg0 int32) int32

func (self *SigningKey) Extractable() bool {

	result := wasm_import_method_signing_key_extractable((self).Handle())
	return (result != 0)

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [method]signing-key.can-sign
func wasm_import_method_signing_key_can_sign(arg0 int32) int32

func (self *SigningKey) CanSign() bool {

	result := wasm_import_method_signing_key_can_sign((self).Handle())
	return (result != 0)

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]signing-key.export-key-jwk
func wasm_import_method_signing_key_export_key_jwk(arg0 int32, arg1 uintptr) int32

func (self *SigningKey) ExportKeyJwk() witTypes.Result[string, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_signing_key_export_key_jwk((self).Handle(), returnArea)))
	var result witTypes.Result[string, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[string, polymorph_webcrypto_types.Error](value)
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value1)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value2)

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value4)

		case 7:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value5, value6, value7})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[string, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]signing-key.export-key-pkcs8
func wasm_import_method_signing_key_export_key_pkcs8(arg0 int32, arg1 uintptr) int32

func (self *SigningKey) ExportKeyPkcs8() witTypes.Result[[]uint8, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_signing_key_export_key_pkcs8((self).Handle(), returnArea)))
	var result witTypes.Result[[]uint8, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, polymorph_webcrypto_types.Error](value)
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value1)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value2)

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value4)

		case 7:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value5, value6, value7})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[[]uint8, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]signing-key.to-wrap-input-jwk
func wasm_import_method_signing_key_to_wrap_input_jwk(arg0 int32, arg1 uintptr) int32

func (self *SigningKey) ToWrapInputJwk() witTypes.Result[*polymorph_webcrypto_wrapping.WrapInput, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_signing_key_to_wrap_input_jwk((self).Handle(), returnArea)))
	var result witTypes.Result[*polymorph_webcrypto_wrapping.WrapInput, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*polymorph_webcrypto_wrapping.WrapInput, polymorph_webcrypto_types.Error](polymorph_webcrypto_wrapping.WrapInputFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value0)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value1)

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value3)

		case 7:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value4, value5, value6})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*polymorph_webcrypto_wrapping.WrapInput, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport polymorph:webcrypto/signature@0.1.0 [async-lower][method]signing-key.to-wrap-input-pkcs8
func wasm_import_method_signing_key_to_wrap_input_pkcs8(arg0 int32, arg1 uintptr) int32

func (self *SigningKey) ToWrapInputPkcs8() witTypes.Result[*polymorph_webcrypto_wrapping.WrapInput, polymorph_webcrypto_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_signing_key_to_wrap_input_pkcs8((self).Handle(), returnArea)))
	var result witTypes.Result[*polymorph_webcrypto_wrapping.WrapInput, polymorph_webcrypto_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*polymorph_webcrypto_wrapping.WrapInput, polymorph_webcrypto_types.Error](polymorph_webcrypto_wrapping.WrapInputFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant polymorph_webcrypto_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidKey(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorInvalidNonce(value0)

		case 2:

			variant = polymorph_webcrypto_types.MakeErrorAuthenticationFailed()

		case 3:

			variant = polymorph_webcrypto_types.MakeErrorNotExtractable()

		case 4:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorUnsupported(value1)

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorNotPermitted(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorOther(value3)

		case 7:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			variant = polymorph_webcrypto_types.MakeErrorExtension(polymorph_webcrypto_types.ExtensionError{value4, value5, value6})

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*polymorph_webcrypto_wrapping.WrapInput, polymorph_webcrypto_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}
