// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package polymorph_iroh_identity

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
)

type EndpointId = []uint8

//go:wasmimport polymorph:iroh/identity@0.1.0 [resource-drop]identity
func resourceDropIdentity(handle int32)

// An endpoint identity: an Ed25519 key pair whose private half
// lives behind the component's crypto import and is never present
// in this component's memory.
//
// An identity is valid by construction — every constructor
// interface validates before minting — and reusable: any number
// of `endpoint-options` may be built from one identity (endpoints
// sharing an identity share the key, not connection state).
type Identity struct {
	handle *witRuntime.Handle
}

func (self *Identity) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Identity) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Identity) Handle() int32 {
	return self.handle.Use()
}

func (self *Identity) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropIdentity(handle)
	}
}

func IdentityFromOwnHandle(handleValue int32) *Identity {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Identity{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropIdentity(handleValue)
		}
	}, 0)
	return value
}

func IdentityFromBorrowHandle(handleValue int32) *Identity {
	handle := witRuntime.MakeHandle(handleValue)
	return &Identity{handle}
}

//go:wasmimport polymorph:iroh/identity@0.1.0 [method]identity.endpoint-id
func wasm_import_method_identity_endpoint_id(arg0 int32, arg1 uintptr)

func (self *Identity) EndpointId() []uint8 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_identity_endpoint_id((self).Handle(), returnArea)
	value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}
