// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package wosh_terminal_terminal

import ()

const (
	// Dialing over iroh, or the SSH transport handshake is running.
	StatusConnecting uint8 = 0
	// Key exchange finished: `host-key-fingerprint` is readable and
	// the session is parked here until `confirm-host-key` resolves
	// it. Nothing has been sent to the server yet -- not a password,
	// not even a public-key probe.
	StatusHostKeyCheck uint8 = 1
	// The host key was accepted; authentication is in flight.
	StatusAuthenticating uint8 = 2
	// Pty and shell are up; `write-input`/`drain-output` carry the
	// interactive session.
	StatusReady uint8 = 3
	// Terminal state: the dial, handshake, auth, or shell failed, or
	// the session ended. The string is a human-readable reason.
	StatusClosed uint8 = 4
)

// Where the session currently stands.
type Status struct {
	tag   uint8
	value any
}

func (self Status) Tag() uint8 {
	return self.tag
}

func (self Status) Closed() string {
	if self.tag != StatusClosed {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeStatusConnecting() Status {
	return Status{StatusConnecting, nil}
}
func MakeStatusHostKeyCheck() Status {
	return Status{StatusHostKeyCheck, nil}
}
func MakeStatusAuthenticating() Status {
	return Status{StatusAuthenticating, nil}
}
func MakeStatusReady() Status {
	return Status{StatusReady, nil}
}
func MakeStatusClosed(value string) Status {
	return Status{StatusClosed, value}
}
