// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     wosh:terminal

package main

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_wosh_terminal_terminal"
	"wit_component/wosh_terminal_terminal"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport [async-lift]wosh:terminal/terminal#keepalive
func wasm_export_wosh_terminal_terminal_keepalive() int32 {
	return int32(witAsync.Run(func() {

		export_wosh_terminal_terminal.Keepalive()
		wasm_export_task_return_wosh_terminal_terminal_keepalive()

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#keepalive
func wasm_export_callback_wosh_terminal_terminal_keepalive(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return]keepalive
func wasm_export_task_return_wosh_terminal_terminal_keepalive()

//go:wasmexport [async-lift]wosh:terminal/terminal#identity-openssh
func wasm_export_wosh_terminal_terminal_identity_openssh() int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := export_wosh_terminal_terminal.IdentityOpenssh()
		var option int32
		var option1 uintptr
		var option2 uint32
		switch result.Tag() {
		case witTypes.ResultOk:
			payload := result.Ok()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(0)
			option1 = uintptr(utf8)
			option2 = uint32(len(payload))
		case witTypes.ResultErr:
			payload := result.Err()
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)

			option = int32(1)
			option1 = uintptr(utf80)
			option2 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_identity_openssh(option, option1, option2)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#identity-openssh
func wasm_export_callback_wosh_terminal_terminal_identity_openssh(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return]identity-openssh
func wasm_export_task_return_wosh_terminal_terminal_identity_openssh(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[static]session.connect
func wasm_export_wosh_terminal_terminal_static_session_connect(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 int32, arg5 int32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
		value0 := unsafe.String((*uint8)(unsafe.Pointer(arg2)), arg3)
		witRuntime.Unpin()
		result := export_wosh_terminal_terminal.SessionConnect(value, value0, uint16(arg4), uint16(arg5))
		var option int32
		var option1 uintptr
		var option2 uint32
		switch result.Tag() {
		case witTypes.ResultOk:
			payload := result.Ok()

			option = int32(0)
			option1 = uintptr((payload).TakeHandle())
			option2 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option1 = uintptr(utf8)
			option2 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_static_session_connect(option, option1, option2)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[static]session.connect
func wasm_export_callback_wosh_terminal_terminal_static_session_connect(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][static]session.connect
func wasm_export_task_return_wosh_terminal_terminal_static_session_connect(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.status
func wasm_export_wosh_terminal_terminal_method_session_status(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).Status()
		var variant int32
		var variant0 uintptr
		var variant1 uint32
		switch result.Tag() {
		case wosh_terminal_terminal.StatusConnecting:

			variant = int32(0)
			variant0 = 0
			variant1 = 0

		case wosh_terminal_terminal.StatusHostKeyCheck:

			variant = int32(1)
			variant0 = 0
			variant1 = 0

		case wosh_terminal_terminal.StatusAuthenticating:

			variant = int32(2)
			variant0 = 0
			variant1 = 0

		case wosh_terminal_terminal.StatusAuthPrompts:

			variant = int32(3)
			variant0 = 0
			variant1 = 0

		case wosh_terminal_terminal.StatusReady:

			variant = int32(4)
			variant0 = 0
			variant1 = 0

		case wosh_terminal_terminal.StatusClosed:
			payload := result.Closed()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			variant = int32(5)
			variant0 = uintptr(utf8)
			variant1 = uint32(len(payload))

		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_status(variant, variant0, variant1)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.status
func wasm_export_callback_wosh_terminal_terminal_method_session_status(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.status
func wasm_export_task_return_wosh_terminal_terminal_method_session_status(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.host-key-fingerprint
func wasm_export_wosh_terminal_terminal_method_session_host_key_fingerprint(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).HostKeyFingerprint()
		var option int32
		var option0 uintptr
		var option1 uint32
		switch result.Tag() {
		case witTypes.OptionNone:

			option = int32(0)
			option0 = 0
			option1 = 0
		case witTypes.OptionSome:
			payload := result.Some()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option0 = uintptr(utf8)
			option1 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_host_key_fingerprint(option, option0, option1)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.host-key-fingerprint
func wasm_export_callback_wosh_terminal_terminal_method_session_host_key_fingerprint(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.host-key-fingerprint
func wasm_export_task_return_wosh_terminal_terminal_method_session_host_key_fingerprint(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.confirm-host-key
func wasm_export_wosh_terminal_terminal_method_session_confirm_host_key(arg0 uintptr, arg1 int32) int32 {
	return int32(witAsync.Run(func() {

		(export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).ConfirmHostKey((arg1 != 0))
		wasm_export_task_return_wosh_terminal_terminal_method_session_confirm_host_key()

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.confirm-host-key
func wasm_export_callback_wosh_terminal_terminal_method_session_confirm_host_key(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.confirm-host-key
func wasm_export_task_return_wosh_terminal_terminal_method_session_confirm_host_key()

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.authenticate-password
func wasm_export_wosh_terminal_terminal_method_session_authenticate_password(arg0 uintptr, arg1 uintptr, arg2 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		value := unsafe.String((*uint8)(unsafe.Pointer(arg1)), arg2)
		witRuntime.Unpin()
		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).AuthenticatePassword(value)
		var option int32
		var option0 uintptr
		var option1 uint32
		switch result.Tag() {
		case witTypes.ResultOk:

			option = int32(0)
			option0 = 0
			option1 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option0 = uintptr(utf8)
			option1 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_authenticate_password(option, option0, option1)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.authenticate-password
func wasm_export_callback_wosh_terminal_terminal_method_session_authenticate_password(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.authenticate-password
func wasm_export_task_return_wosh_terminal_terminal_method_session_authenticate_password(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.authenticate-publickey
func wasm_export_wosh_terminal_terminal_method_session_authenticate_publickey(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).AuthenticatePublickey()
		var option int32
		var option0 uintptr
		var option1 uint32
		switch result.Tag() {
		case witTypes.ResultOk:

			option = int32(0)
			option0 = 0
			option1 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option0 = uintptr(utf8)
			option1 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_authenticate_publickey(option, option0, option1)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.authenticate-publickey
func wasm_export_callback_wosh_terminal_terminal_method_session_authenticate_publickey(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.authenticate-publickey
func wasm_export_task_return_wosh_terminal_terminal_method_session_authenticate_publickey(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.authenticate-interactive
func wasm_export_wosh_terminal_terminal_method_session_authenticate_interactive(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).AuthenticateInteractive()
		var option int32
		var option0 uintptr
		var option1 uint32
		switch result.Tag() {
		case witTypes.ResultOk:

			option = int32(0)
			option0 = 0
			option1 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option0 = uintptr(utf8)
			option1 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_authenticate_interactive(option, option0, option1)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.authenticate-interactive
func wasm_export_callback_wosh_terminal_terminal_method_session_authenticate_interactive(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.authenticate-interactive
func wasm_export_task_return_wosh_terminal_terminal_method_session_authenticate_interactive(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.authenticate-auto
func wasm_export_wosh_terminal_terminal_method_session_authenticate_auto(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).AuthenticateAuto()
		var option int32
		var option0 uintptr
		var option1 uint32
		switch result.Tag() {
		case witTypes.ResultOk:

			option = int32(0)
			option0 = 0
			option1 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option0 = uintptr(utf8)
			option1 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_authenticate_auto(option, option0, option1)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.authenticate-auto
func wasm_export_callback_wosh_terminal_terminal_method_session_authenticate_auto(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.authenticate-auto
func wasm_export_task_return_wosh_terminal_terminal_method_session_authenticate_auto(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.pending-prompts
func wasm_export_wosh_terminal_terminal_method_session_pending_prompts(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).PendingPrompts()
		var option int32
		var option3 uintptr
		var option4 uint32
		var option5 uintptr
		var option6 uint32
		switch result.Tag() {
		case witTypes.OptionNone:

			option = int32(0)
			option3 = 0
			option4 = 0
			option5 = 0
			option6 = 0
		case witTypes.OptionSome:
			payload := result.Some()
			utf8 := unsafe.Pointer(unsafe.StringData((payload).Instruction))
			pinner.Pin(utf8)
			slice := (payload).Prompts
			length := uint32(len(slice))
			result2 := witRuntime.Allocate(pinner, uintptr(length*(3*4)), 4)
			for index, element := range slice {
				base := unsafe.Add(result2, index*(3*4))
				utf80 := unsafe.Pointer(unsafe.StringData((element).Text))
				pinner.Pin(utf80)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Text)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf80)))
				var result1 int32
				if (element).Echo {
					result1 = 1
				} else {
					result1 = 0
				}
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(result1)

			}

			option = int32(1)
			option3 = uintptr(utf8)
			option4 = uint32(len((payload).Instruction))
			option5 = uintptr(result2)
			option6 = length
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_pending_prompts(option, option3, option4, option5, option6)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.pending-prompts
func wasm_export_callback_wosh_terminal_terminal_method_session_pending_prompts(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.pending-prompts
func wasm_export_task_return_wosh_terminal_terminal_method_session_pending_prompts(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.answer-prompts
func wasm_export_wosh_terminal_terminal_method_session_answer_prompts(arg0 uintptr, arg1 uintptr, arg2 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := make([]string, 0, arg2)
		for index := 0; index < int(arg2); index++ {
			base := unsafe.Add(unsafe.Pointer(arg1), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		witRuntime.Unpin()
		result0 := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).AnswerPrompts(result)
		var option int32
		var option1 uintptr
		var option2 uint32
		switch result0.Tag() {
		case witTypes.ResultOk:

			option = int32(0)
			option1 = 0
			option2 = 0
		case witTypes.ResultErr:
			payload := result0.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option1 = uintptr(utf8)
			option2 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_answer_prompts(option, option1, option2)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.answer-prompts
func wasm_export_callback_wosh_terminal_terminal_method_session_answer_prompts(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.answer-prompts
func wasm_export_task_return_wosh_terminal_terminal_method_session_answer_prompts(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.write-input
func wasm_export_wosh_terminal_terminal_method_session_write_input(arg0 uintptr, arg1 uintptr, arg2 uint32) int32 {
	return int32(witAsync.Run(func() {

		value := unsafe.Slice((*uint8)(unsafe.Pointer(arg1)), arg2)
		witRuntime.Unpin()
		(export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).WriteInput(value)
		wasm_export_task_return_wosh_terminal_terminal_method_session_write_input()

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.write-input
func wasm_export_callback_wosh_terminal_terminal_method_session_write_input(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.write-input
func wasm_export_task_return_wosh_terminal_terminal_method_session_write_input()

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.resize
func wasm_export_wosh_terminal_terminal_method_session_resize(arg0 uintptr, arg1 int32, arg2 int32) int32 {
	return int32(witAsync.Run(func() {

		(export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).Resize(uint16(arg1), uint16(arg2))
		wasm_export_task_return_wosh_terminal_terminal_method_session_resize()

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.resize
func wasm_export_callback_wosh_terminal_terminal_method_session_resize(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.resize
func wasm_export_task_return_wosh_terminal_terminal_method_session_resize()

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.drain-output
func wasm_export_wosh_terminal_terminal_method_session_drain_output(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).DrainOutput()
		data := unsafe.Pointer(unsafe.SliceData(result))
		pinner.Pin(data)
		wasm_export_task_return_wosh_terminal_terminal_method_session_drain_output(uintptr(data), uint32(len(result)))

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.drain-output
func wasm_export_callback_wosh_terminal_terminal_method_session_drain_output(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.drain-output
func wasm_export_task_return_wosh_terminal_terminal_method_session_drain_output(arg0 uintptr, arg1 uint32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.exited
func wasm_export_wosh_terminal_terminal_method_session_exited(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {

		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).Exited()
		var result0 int32
		if result {
			result0 = 1
		} else {
			result0 = 0
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_exited(result0)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.exited
func wasm_export_callback_wosh_terminal_terminal_method_session_exited(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.exited
func wasm_export_task_return_wosh_terminal_terminal_method_session_exited(arg0 int32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.exit-status
func wasm_export_wosh_terminal_terminal_method_session_exit_status(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {

		result := (export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).ExitStatus()
		var option int32
		var option0 int32
		switch result.Tag() {
		case witTypes.OptionNone:

			option = int32(0)
			option0 = 0
		case witTypes.OptionSome:
			payload := result.Some()

			option = int32(1)
			option0 = payload
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wosh_terminal_terminal_method_session_exit_status(option, option0)

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.exit-status
func wasm_export_callback_wosh_terminal_terminal_method_session_exit_status(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.exit-status
func wasm_export_task_return_wosh_terminal_terminal_method_session_exit_status(arg0 int32, arg1 int32)

//go:wasmexport [async-lift]wosh:terminal/terminal#[method]session.detach
func wasm_export_wosh_terminal_terminal_method_session_detach(arg0 uintptr) int32 {
	return int32(witAsync.Run(func() {

		(export_wosh_terminal_terminal.SessionFromBorrowHandle(int32(uintptr(arg0)))).Detach()
		wasm_export_task_return_wosh_terminal_terminal_method_session_detach()

	}))
}

//go:wasmexport [callback][async-lift]wosh:terminal/terminal#[method]session.detach
func wasm_export_callback_wosh_terminal_terminal_method_session_detach(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wosh:terminal/terminal [task-return][method]session.detach
func wasm_export_task_return_wosh_terminal_terminal_method_session_detach()

// Unused, but present to make the compiler happy
func main() {}
