// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wosh:ssh-core

package wosh_ssh_core_core

import ()

const (
	// The transport handshake is running on fed bytes.
	StatusConnecting uint8 = 0
	// Key exchange finished: `host-key-sha256` is readable and the
	// handshake is parked until `confirm-host-key` resolves it.
	// Nothing has been sent to the server yet -- not a password, not
	// even a public-key probe. That ordering is structural:
	// x/crypto/ssh authenticates strictly after a successful
	// host-key callback.
	StatusHostKeyCheck uint8 = 1
	// The host key was accepted; authentication is in flight.
	StatusAuthenticating uint8 = 2
	// Authentication is parked on a signature request: read
	// `pending-signature`, produce the signature, call
	// `provide-signature` (or `fail-signature`).
	StatusSigning uint8 = 3
	// Authentication is parked on a server-issued prompt batch: read
	// `pending-prompts`, collect answers, call `answer-prompts`.
	StatusAuthPrompts uint8 = 4
	// Pty and shell are up; `write-input`/`drain-output` carry the
	// interactive session.
	StatusReady uint8 = 5
	// Terminal state: the handshake, auth, or shell failed, or the
	// session ended. The string is a human-readable reason.
	StatusClosed uint8 = 6
)

// Where the session currently stands.
type Status struct {
	tag   uint8
	value any
}

func (self Status) Tag() uint8 {
	return self.tag
}

func (self Status) Closed() string {
	if self.tag != StatusClosed {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeStatusConnecting() Status {
	return Status{StatusConnecting, nil}
}
func MakeStatusHostKeyCheck() Status {
	return Status{StatusHostKeyCheck, nil}
}
func MakeStatusAuthenticating() Status {
	return Status{StatusAuthenticating, nil}
}
func MakeStatusSigning() Status {
	return Status{StatusSigning, nil}
}
func MakeStatusAuthPrompts() Status {
	return Status{StatusAuthPrompts, nil}
}
func MakeStatusReady() Status {
	return Status{StatusReady, nil}
}
func MakeStatusClosed(value string) Status {
	return Status{StatusClosed, value}
}

// One keyboard-interactive prompt: the text to display, and whether
// the user's answer should be echoed as typed (`false` means mask
// it, password-style).
type Prompt struct {
	Text string
	Echo bool
}

// One server-issued batch of prompts (RFC 4256). The server
// drives: any number of batches, each with any number of prompts.
// `authenticate-auto`'s password round rides the same shape as a
// one-prompt masked batch.
type PromptBatch struct {
	// Free-text preamble to display above the prompts. Often empty;
	// PAM setups use it for OTP guidance and expiry warnings.
	Instruction string
	Prompts     []Prompt
}
