// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     polymorph:webcrypto@0.1.0
//     polymorph:webrtc-datachannels@0.1.0
//     polymorph:websocket@0.1.0
//     wasi:clocks@0.3.0
//     wasi:sockets@0.3.0
//     polymorph:iroh@0.1.0
//     irsh:terminal

package polymorph_webcrypto_types

import ()

// A named error condition defined outside `error`'s closed set: by an
// algorithm interface's contract (the first is `sha1-checked`'s
// `collision-detected`), a future feature's, or a third-party
// provider's. The (`origin`, `name`) pair is the condition's only
// branchable identity; the defining interface documents when the
// condition occurs. Conditions are nominal: the pair identifies, the
// message elaborates for humans, and no field carries machine-readable
// data. See `README.md`, "Error contract", including the rule for
// pairs a caller does not recognize.
type ExtensionError struct {
	// The namespace the condition is defined under: an opaque string
	// owned by the defining party, by convention its package name,
	// e.g. `"polymorph:webcrypto"`. Ownership means names cannot collide:
	// third-party providers mint conditions under their own
	// namespace, never under another party's.
	Origin string
	// The condition's name within `origin`, kebab-case by convention,
	// e.g. `"collision-detected"`.
	Name string
	// Human-readable prose for logs and diagnostics only. Never
	// branch on it: its content is not contract and may differ
	// across providers. Empty where the condition's contract is
	// deliberately detail-free.
	Message string
}

const (
	// The supplied key material is invalid for the algorithm (for
	// example, a wrong-length raw key, or one rejected by an
	// implementation's key-length policy). The string is
	// human-readable.
	ErrorInvalidKey uint8 = 0
	// The supplied nonce is invalid for the algorithm (for example, a
	// wrong-length AES-GCM nonce). The string is human-readable.
	ErrorInvalidNonce uint8 = 1
	// Verification failed: the input is unauthenticated under the key.
	//
	// Security:
	//   - Failed verification MUST report this case and nothing else.
	//     Security telemetry may rely on it never being misfiled.
	//   - The case deliberately carries no detail, so implementations
	//     cannot leak *why* verification failed.
	//   - Rare operational false positives are possible on `open`,
	//     never on `verify`. See `README.md`, "Error contract".
	ErrorAuthenticationFailed uint8 = 2
	// The key was created with `extractable` false, so its material
	// cannot be exported.
	ErrorNotExtractable uint8 = 3
	// The request was well-formed, but this implementation does not
	// serve the requested algorithm parameters (for example, a key
	// size the platform's crypto API declines). The string is
	// human-readable.
	ErrorUnsupported uint8 = 4
	// The key does not permit the requested operation: the operation's
	// usage was not granted at mint. The string names the refused
	// operation. Distinct from `unsupported` (the implementation
	// serves the operation; this key refuses it) and never a verdict
	// on the input.
	ErrorNotPermitted uint8 = 5
	// An implementation-specific operational failure: for example, an
	// external keystore that cannot complete the operation now, or an
	// input exceeding an implementation's buffering limit. The string
	// is human-readable.
	// Never a semantic condition a caller must branch on: a
	// condition that turns out to need branching migrates to a named
	// `extension` pair (see `README.md`, "Error contract").
	ErrorOther uint8 = 6
	// A named condition outside this variant's closed set (see
	// `extension-error`). Unlike `other`, callers may branch on it:
	// the defining interface's contract says when it occurs. See
	// `README.md`, "Error contract", for which conditions belong in
	// the closed cases and which here.
	ErrorExtension uint8 = 7
)

// Errors surfaced by key creation and cryptographic operations.
//
// There is no case for API misuse: the package aims to make misuse
// inexpressible instead of reporting it (see `README.md`, "Design
// notes"). See also `README.md`, "Error contract".
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) InvalidKey() string {
	if self.tag != ErrorInvalidKey {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) InvalidNonce() string {
	if self.tag != ErrorInvalidNonce {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) Unsupported() string {
	if self.tag != ErrorUnsupported {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) NotPermitted() string {
	if self.tag != ErrorNotPermitted {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) Extension() ExtensionError {
	if self.tag != ErrorExtension {
		panic("tag mismatch")
	}
	return self.value.(ExtensionError)
}

func MakeErrorInvalidKey(value string) Error {
	return Error{ErrorInvalidKey, value}
}
func MakeErrorInvalidNonce(value string) Error {
	return Error{ErrorInvalidNonce, value}
}
func MakeErrorAuthenticationFailed() Error {
	return Error{ErrorAuthenticationFailed, nil}
}
func MakeErrorNotExtractable() Error {
	return Error{ErrorNotExtractable, nil}
}
func MakeErrorUnsupported(value string) Error {
	return Error{ErrorUnsupported, value}
}
func MakeErrorNotPermitted(value string) Error {
	return Error{ErrorNotPermitted, value}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}
func MakeErrorExtension(value ExtensionError) Error {
	return Error{ErrorExtension, value}
}
